In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime
%matplotlib inline
import seaborn as sns
sns.set_context('poster')

## Models With MSA, Years and Features

### Import, Split, and Standardize Data

In [2]:
start = datetime.datetime.time(datetime.datetime.now())

In [3]:
df = pd.read_pickle('../data/merged/all_data_2006_to_2016.pkl')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 928 entries, 0 to 927
Data columns (total 13 columns):
year                                                                           928 non-null int64
MSA_orig                                                                       928 non-null object
MSA                                                                            928 non-null object
MSA_abbr                                                                       928 non-null object
now_married_except_separated                                                   928 non-null float64
less_than_high_school_diploma                                                  928 non-null float64
unmarried_portion_of_women_15_to_50_years_who_had_a_birth_in_past_12_months    928 non-null float64
households_with_food_stamp_snap_benefits                                       928 non-null float64
percentage_married_couple_family                                               928 non-null float64
percentage_female_householder_no_husband_present_family                        928 non-null float64
poverty_all_people                                                             928 non-null float64
house_median_value_(dollars)                                                   928 non-null int64
murder_per_100_k                                                               928 non-null float64
dtypes: float64(8), int64(2), object(3)
memory usage: 94.3+ KB

In [5]:
# drop extra MSA names
df = df.drop(['MSA_orig', 'MSA'], axis=1)

In [6]:
# remove outliers with atypically high murder rates
df = df[df.MSA_abbr != 'NEW_ORLEANS_LA']
df = df[(df.MSA_abbr != 'MEMPHIS_TN') | (df.year != 2016)]
df = df[(df.MSA_abbr != 'BATON_ROUGE_LA') | (df.year != 2007)]

In [7]:
df = pd.get_dummies(df, columns=['MSA_abbr'], drop_first=True)
df.head()

,year,now_married_except_separated,less_than_high_school_diploma,unmarried_portion_of_women_15_to_50_years_who_had_a_birth_in_past_12_months,households_with_food_stamp_snap_benefits,percentage_married_couple_family,percentage_female_householder_no_husband_present_family,poverty_all_people,house_median_value_(dollars),murder_per_100_k,...,MSA_abbr_TAMPA_FL,MSA_abbr_TOLEDO_OH,MSA_abbr_TUCSON_AZ,MSA_abbr_TULSA_OK,MSA_abbr_VIRGINIA_BEACH_NC,MSA_abbr_WASHINGTON_DC,MSA_abbr_WICHITA_KS,MSA_abbr_WINSTON_NC,MSA_abbr_WORCESTER_MA,MSA_abbr_YOUNGSTOWN_OH
0,2007,50.5,9.9,28.0,8.8,75.7,18.0,13.4,147000,3.6,...,0,0,0,0,0,0,0,0,0,0
1,2008,49.3,9.9,35.9,9.5,74.3,19.9,12.1,148300,3.4,...,0,0,0,0,0,0,0,0,0,0
2,2009,48.1,10.1,42.4,12.0,73.2,20.7,14.7,142500,4.0,...,0,0,0,0,0,0,0,0,0,0
3,2010,47.9,10.7,41.0,12.9,73.7,19.8,15.5,145000,3.7,...,0,0,0,0,0,0,0,0,0,0
4,2011,46.8,9.1,38.2,14.5,72.9,21.7,16.6,139800,4.7,...,0,0,0,0,0,0,0,0,0,0

In [8]:
# separate labels and features

label_col = 'murder_per_100_k'

x = df.drop([label_col], axis=1)
y = df[label_col]

print('Sizes match: {}'.format(len(x)==len(y)))

Sizes match: True

In [9]:
# train test split

from sklearn.model_selection import train_test_split

x_train_s, x_test_s, y_train, y_test = train_test_split(x,y, test_size=0.3)

print('Len x_train: {}'.format(len(x_train_s)))
print('Len x_test: {}'.format(len(x_test_s)))
print('Len y_train: {}'.format(len(y_train)))
print('Len x_test: {}'.format(len(y_test)))

Len x_train: 641
Len x_test: 275
Len y_train: 641
Len x_test: 275

In [10]:
# standardize data

from sklearn.preprocessing import StandardScaler
standardizer = StandardScaler().fit(x_train_s)

x_train = standardizer.transform(x_train_s)
x_test = standardizer.transform(x_test_s)

### Simple Linear Regression

In [11]:
from sklearn.linear_model import LinearRegression, RidgeCV, LassoCV, BayesianRidge, HuberRegressor
from sklearn.model_selection import GridSearchCV

In [12]:
# instantiate and fit models

def make_models(x_train, y_train):
    md = dict()

    md['linear'] = LinearRegression().fit(x_train, y_train)
    md['ridge'] = RidgeCV(cv=15).fit(x_train, y_train)
    md['lasso'] = LassoCV(cv=15).fit(x_train, y_train)
    md['bayes'] = BayesianRidge(tol=0.0001).fit(x_train, y_train)
    md['huber'] = GridSearchCV(HuberRegressor(),{'epsilon': [1.0,1.1,1.2,1.3,1.4,1.5,1.6,1.7]}).fit(x_train, y_train).best_estimator_
    
    return md

In [13]:
# score models

def score_model(model):

    train_score = model.score(x_train, y_train)
    test_score = model.score(x_test, y_test)

    return np.array([train_score, test_score])

In [14]:
def results_df(model):

    # get train and test scores
    scores_df = pd.DataFrame(score_model(model)).transpose()
    scores_df.columns = ['Train R2','Test R2']

    # get coefficient matrix
    coeffs_df = pd.DataFrame(model.coef_).transpose()
    coeffs_df.columns = x.columns

    # join dataframes
    return pd.concat([scores_df, coeffs_df], axis=1)

In [15]:
from sklearn.utils import resample

In [16]:
def run_experiment(n_iters):
    
    sample_results = dict()
    
    for n in range(n_iters):
        # get new sample
        xb, yb = resample(x_train, y_train)

        # make and fit models
        model_dict = make_models(xb, yb)

        # get sample of results for each model
        for key in model_dict:
            
            # initialize empty dictionary
            if key not in sample_results:
                sample_results[key] = []
                        
            # get model results
            sample_results[key].append(results_df(model_dict[key]))
            
    # concatenate results dfs into single df
    for key in sample_results:
        sample_results[key] = pd.concat(sample_results[key])
        
    return sample_results

In [17]:
exp = run_experiment(200)

In [18]:
coef_dict = dict()

# iterate over all models
for key in exp:
    
    # iterate over results of this model
    for c in exp[key].columns:
        
        # initialize dict for result names
        if c not in coef_dict:
            coef_dict[c] = dict()
    
        # add this coeff to the dict
        coef_dict[c][key] = exp[key][c]

# convert dict of dicts into dict of dataframes
coef_dfs = {key: pd.DataFrame(coef_dict[key]) for key in coef_dict}

In [19]:
for key in exp:
    print(key)
    print()
    print(exp[key].mean())
    print()

linear

Train R2                                                                      -1.036832e+26
Test R2                                                                       -2.013558e+26
year                                                                          -1.488793e-01
now_married_except_separated                                                   2.424507e-01
less_than_high_school_diploma                                                 -6.484630e-01
unmarried_portion_of_women_15_to_50_years_who_had_a_birth_in_past_12_months    7.741808e-02
households_with_food_stamp_snap_benefits                                      -2.360427e-01
percentage_married_couple_family                                              -2.028214e-01
percentage_female_householder_no_husband_present_family                       -6.513739e-01
poverty_all_people                                                            -2.067305e-01
house_median_value_(dollars)                                                   3.290281e-01
MSA_abbr_ALBANY_NY                                                            -2.968470e-01
MSA_abbr_ALBUQUERQUE_NM                                                        8.258813e+09
MSA_abbr_ALLENTOWN_PA                                                          2.690254e+11
MSA_abbr_ATLANTA_GA                                                            2.440405e-01
MSA_abbr_AUGUSTA_GA                                                            5.159147e-01
MSA_abbr_AUSTIN_TX                                                            -2.804057e-01
MSA_abbr_BAKERSFIELD_CA                                                        5.576469e-01
MSA_abbr_BALTIMORE_MD                                                          7.435540e-01
MSA_abbr_BATON_ROUGE_LA                                                       -2.532296e+09
MSA_abbr_BIRMINGHAM_AL                                                         1.728451e+09
MSA_abbr_BOISE_ID                                                             -4.581904e-01
MSA_abbr_BOSTON_MA                                                            -2.271466e+10
MSA_abbr_BRADENTON_FL                                                          2.062157e+11
MSA_abbr_BRIDGEPORT_CT                                                         1.156489e+09
MSA_abbr_BUFFALO_NY                                                           -1.020050e+10
MSA_abbr_CAPE_CORAL_FL                                                        -1.299096e+08
MSA_abbr_CHARLESTON_SC                                                         6.417603e+09
MSA_abbr_CHARLOTTE_NC                                                          4.980751e+09
MSA_abbr_CHATANOOGA_TN                                                         3.455947e+11
                                                                                   ...
MSA_abbr_PORTLAND_OR                                                          -2.273283e+11
MSA_abbr_POUGHKEEPSIE_NY                                                       2.022085e+11
MSA_abbr_PROVIDENCE_RI                                                        -1.208988e-01
MSA_abbr_PROVO_UT                                                             -7.037310e-01
MSA_abbr_RALEIGH_NC                                                           -2.449727e-01
MSA_abbr_RICHMOND_VA                                                           2.837257e-01
MSA_abbr_RIVERSIDE_CA                                                          1.298271e-01
MSA_abbr_ROCHESTER_NY                                                          2.894448e-03
MSA_abbr_SALT_LAKE_CITY_UT                                                    -4.391680e-01
MSA_abbr_SANTA_ROSA_CA                                                        -5.607678e+11
MSA_abbr_SAN_ANTONIO_TX                                                        3.000667e+11
MSA_abbr_SAN_DIEGO_CA                                                          1.221260e+11
MSA_abbr_SAN_FRANCISCO_CA                                                     -7.781632e+09
MSA_abbr_SAN_JOSE_CA                                                          -4.924394e-01
MSA_abbr_SEATTLE_WA                                                           -1.072797e+09
MSA_abbr_SPOKANE_WA                                                           -1.074765e+11
MSA_abbr_SPRINGFIELD_MA                                                        4.301486e-02
MSA_abbr_STOCKTON_CA                                                           5.157254e-01
MSA_abbr_ST_LOUIS_MO                                                           2.892961e-01
MSA_abbr_SYRACUSE_NY                                                          -4.814622e-02
MSA_abbr_TAMPA_FL                                                              2.019099e-02
MSA_abbr_TOLEDO_OH                                                             9.434260e-02
MSA_abbr_TUCSON_AZ                                                             2.958558e-01
MSA_abbr_TULSA_OK                                                             -5.865579e+09
MSA_abbr_VIRGINIA_BEACH_NC                                                     3.041641e-01
MSA_abbr_WASHINGTON_DC                                                        -7.651374e-02
MSA_abbr_WICHITA_KS                                                           -4.379124e-02
MSA_abbr_WINSTON_NC                                                           -6.172242e+11
MSA_abbr_WORCESTER_MA                                                         -3.790954e-01
MSA_abbr_YOUNGSTOWN_OH                                                        -4.321601e+11
Length: 116, dtype: float64

ridge

Train R2                                                                       0.827442
Test R2                                                                        0.787895
year                                                                          -0.070931
now_married_except_separated                                                   0.199890
less_than_high_school_diploma                                                 -0.045757
unmarried_portion_of_women_15_to_50_years_who_had_a_birth_in_past_12_months    0.089153
households_with_food_stamp_snap_benefits                                      -0.275839
percentage_married_couple_family                                              -0.200697
percentage_female_householder_no_husband_present_family                       -0.256457
poverty_all_people                                                            -0.245662
house_median_value_(dollars)                                                   0.184676
MSA_abbr_ALBANY_NY                                                            -0.274163
MSA_abbr_ALBUQUERQUE_NM                                                        0.182699
MSA_abbr_ALLENTOWN_PA                                                         -0.169631
MSA_abbr_ATLANTA_GA                                                            0.175626
MSA_abbr_AUGUSTA_GA                                                            0.366725
MSA_abbr_AUSTIN_TX                                                            -0.289723
MSA_abbr_BAKERSFIELD_CA                                                        0.329030
MSA_abbr_BALTIMORE_MD                                                          0.679818
MSA_abbr_BATON_ROUGE_LA                                                        0.550585
MSA_abbr_BIRMINGHAM_AL                                                         0.481658
MSA_abbr_BOISE_ID                                                             -0.386227
MSA_abbr_BOSTON_MA                                                            -0.264564
MSA_abbr_BRADENTON_FL                                                         -0.050729
MSA_abbr_BRIDGEPORT_CT                                                        -0.321519
MSA_abbr_BUFFALO_NY                                                            0.072464
MSA_abbr_CAPE_CORAL_FL                                                         0.129459
MSA_abbr_CHARLESTON_SC                                                         0.252500
MSA_abbr_CHARLOTTE_NC                                                          0.113343
MSA_abbr_CHATANOOGA_TN                                                         0.072136
                                                                                 ...
MSA_abbr_PORTLAND_OR                                                          -0.245021
MSA_abbr_POUGHKEEPSIE_NY                                                      -0.094341
MSA_abbr_PROVIDENCE_RI                                                        -0.195244
MSA_abbr_PROVO_UT                                                             -0.527359
MSA_abbr_RALEIGH_NC                                                           -0.221127
MSA_abbr_RICHMOND_VA                                                           0.200867
MSA_abbr_RIVERSIDE_CA                                                          0.013917
MSA_abbr_ROCHESTER_NY                                                         -0.044282
MSA_abbr_SALT_LAKE_CITY_UT                                                    -0.381278
MSA_abbr_SANTA_ROSA_CA                                                        -0.256607
MSA_abbr_SAN_ANTONIO_TX                                                        0.144692
MSA_abbr_SAN_DIEGO_CA                                                         -0.290783
MSA_abbr_SAN_FRANCISCO_CA                                                     -0.027743
MSA_abbr_SAN_JOSE_CA                                                          -0.423872
MSA_abbr_SEATTLE_WA                                                           -0.235410
MSA_abbr_SPOKANE_WA                                                           -0.084782
MSA_abbr_SPRINGFIELD_MA                                                       -0.070618
MSA_abbr_STOCKTON_CA                                                           0.354493
MSA_abbr_ST_LOUIS_MO                                                           0.260318
MSA_abbr_SYRACUSE_NY                                                          -0.080940
MSA_abbr_TAMPA_FL                                                             -0.036148
MSA_abbr_TOLEDO_OH                                                             0.042453
MSA_abbr_TUCSON_AZ                                                             0.230821
MSA_abbr_TULSA_OK                                                              0.213395
MSA_abbr_VIRGINIA_BEACH_NC                                                     0.249995
MSA_abbr_WASHINGTON_DC                                                        -0.054938
MSA_abbr_WICHITA_KS                                                           -0.049735
MSA_abbr_WINSTON_NC                                                           -0.016452
MSA_abbr_WORCESTER_MA                                                         -0.369656
MSA_abbr_YOUNGSTOWN_OH                                                         0.103874
Length: 116, dtype: float64

lasso

Train R2                                                                       0.827763
Test R2                                                                        0.787997
year                                                                          -0.043857
now_married_except_separated                                                   0.221780
less_than_high_school_diploma                                                  0.034281
unmarried_portion_of_women_15_to_50_years_who_had_a_birth_in_past_12_months    0.076296
households_with_food_stamp_snap_benefits                                      -0.288326
percentage_married_couple_family                                              -0.193368
percentage_female_householder_no_husband_present_family                       -0.298983
poverty_all_people                                                            -0.214931
house_median_value_(dollars)                                                   0.167644
MSA_abbr_ALBANY_NY                                                            -0.266345
MSA_abbr_ALBUQUERQUE_NM                                                        0.183845
MSA_abbr_ALLENTOWN_PA                                                         -0.166963
MSA_abbr_ATLANTA_GA                                                            0.178760
MSA_abbr_AUGUSTA_GA                                                            0.370681
MSA_abbr_AUSTIN_TX                                                            -0.292942
MSA_abbr_BAKERSFIELD_CA                                                        0.308153
MSA_abbr_BALTIMORE_MD                                                          0.699134
MSA_abbr_BATON_ROUGE_LA                                                        0.560175
MSA_abbr_BIRMINGHAM_AL                                                         0.485160
MSA_abbr_BOISE_ID                                                             -0.397036
MSA_abbr_BOSTON_MA                                                            -0.256350
MSA_abbr_BRADENTON_FL                                                         -0.050441
MSA_abbr_BRIDGEPORT_CT                                                        -0.318601
MSA_abbr_BUFFALO_NY                                                            0.077803
MSA_abbr_CAPE_CORAL_FL                                                         0.119563
MSA_abbr_CHARLESTON_SC                                                         0.258011
MSA_abbr_CHARLOTTE_NC                                                          0.111793
MSA_abbr_CHATANOOGA_TN                                                         0.066414
                                                                                 ...
MSA_abbr_PORTLAND_OR                                                          -0.242659
MSA_abbr_POUGHKEEPSIE_NY                                                      -0.092532
MSA_abbr_PROVIDENCE_RI                                                        -0.190027
MSA_abbr_PROVO_UT                                                             -0.545238
MSA_abbr_RALEIGH_NC                                                           -0.221147
MSA_abbr_RICHMOND_VA                                                           0.205748
MSA_abbr_RIVERSIDE_CA                                                          0.003300
MSA_abbr_ROCHESTER_NY                                                         -0.035228
MSA_abbr_SALT_LAKE_CITY_UT                                                    -0.388700
MSA_abbr_SANTA_ROSA_CA                                                        -0.257006
MSA_abbr_SAN_ANTONIO_TX                                                        0.138931
MSA_abbr_SAN_DIEGO_CA                                                         -0.291522
MSA_abbr_SAN_FRANCISCO_CA                                                     -0.024160
MSA_abbr_SAN_JOSE_CA                                                          -0.429212
MSA_abbr_SEATTLE_WA                                                           -0.232670
MSA_abbr_SPOKANE_WA                                                           -0.079790
MSA_abbr_SPRINGFIELD_MA                                                       -0.055223
MSA_abbr_STOCKTON_CA                                                           0.342462
MSA_abbr_ST_LOUIS_MO                                                           0.265434
MSA_abbr_SYRACUSE_NY                                                          -0.071727
MSA_abbr_TAMPA_FL                                                             -0.031365
MSA_abbr_TOLEDO_OH                                                             0.049079
MSA_abbr_TUCSON_AZ                                                             0.233833
MSA_abbr_TULSA_OK                                                              0.210217
MSA_abbr_VIRGINIA_BEACH_NC                                                     0.262202
MSA_abbr_WASHINGTON_DC                                                        -0.043183
MSA_abbr_WICHITA_KS                                                           -0.049715
MSA_abbr_WINSTON_NC                                                           -0.016482
MSA_abbr_WORCESTER_MA                                                         -0.366147
MSA_abbr_YOUNGSTOWN_OH                                                         0.105506
Length: 116, dtype: float64

bayes

Train R2                                                                       0.825822
Test R2                                                                        0.795815
year                                                                          -0.065597
now_married_except_separated                                                   0.140697
less_than_high_school_diploma                                                  0.191532
unmarried_portion_of_women_15_to_50_years_who_had_a_birth_in_past_12_months    0.111606
households_with_food_stamp_snap_benefits                                      -0.305492
percentage_married_couple_family                                              -0.217078
percentage_female_householder_no_husband_present_family                        0.033578
poverty_all_people                                                            -0.244974
house_median_value_(dollars)                                                   0.062330
MSA_abbr_ALBANY_NY                                                            -0.255157
MSA_abbr_ALBUQUERQUE_NM                                                        0.150543
MSA_abbr_ALLENTOWN_PA                                                         -0.158241
MSA_abbr_ATLANTA_GA                                                            0.137948
MSA_abbr_AUGUSTA_GA                                                            0.272801
MSA_abbr_AUSTIN_TX                                                            -0.278342
MSA_abbr_BAKERSFIELD_CA                                                        0.220470
MSA_abbr_BALTIMORE_MD                                                          0.637967
MSA_abbr_BATON_ROUGE_LA                                                        0.483464
MSA_abbr_BIRMINGHAM_AL                                                         0.429362
MSA_abbr_BOISE_ID                                                             -0.318090
MSA_abbr_BOSTON_MA                                                            -0.232177
MSA_abbr_BRADENTON_FL                                                         -0.041449
MSA_abbr_BRIDGEPORT_CT                                                        -0.268029
MSA_abbr_BUFFALO_NY                                                            0.039153
MSA_abbr_CAPE_CORAL_FL                                                         0.154802
MSA_abbr_CHARLESTON_SC                                                         0.220107
MSA_abbr_CHARLOTTE_NC                                                          0.094285
MSA_abbr_CHATANOOGA_TN                                                         0.054645
                                                                                 ...
MSA_abbr_PORTLAND_OR                                                          -0.206409
MSA_abbr_POUGHKEEPSIE_NY                                                      -0.081651
MSA_abbr_PROVIDENCE_RI                                                        -0.225218
MSA_abbr_PROVO_UT                                                             -0.386713
MSA_abbr_RALEIGH_NC                                                           -0.191752
MSA_abbr_RICHMOND_VA                                                           0.156067
MSA_abbr_RIVERSIDE_CA                                                         -0.025950
MSA_abbr_ROCHESTER_NY                                                         -0.072660
MSA_abbr_SALT_LAKE_CITY_UT                                                    -0.315068

In [20]:
def print_runtime():
    hours = int(str(end)[0:2])-int(str(start)[0:2])
    minutes = int(str(end)[3:5])-int(str(start)[3:5])
    seconds = int(str(end)[6:8])-int(str(start)[6:8])
    if hours < 0:
        hours = hours + 24
    if minutes < 0:
        minutes = minutes + 60
        hours = hours - 1
    if seconds < 0:
        seconds = seconds + 60
        minutes = minutes - 1
    print(hours, "hrs", minutes, "mins", seconds, "secs")

In [21]:
end = datetime.datetime.time(datetime.datetime.now())

In [22]:
print_runtime()

0 hrs 16 mins 20 secs